### ISSUE TITLE
json: cannot unmarshal string into Go value of type multiaddr.Multiaddr

### ISSUE THREAD

**Issue by mg98** [multiformats/go-multiaddr#189]
I'm having trouble to unmarshal JSONs to structs that include `Multiaddr` fields.

`json: cannot unmarshal string into Go struct field .a of type multiaddr.Multiaddr`

```go
var d struct {
	A ma.Multiaddr `json:"a"`
}
if err := json.Unmarshal([]byte(`{"a":"/ip4/64.227.126.216/tcp/4001"}`), &d); err != nil {
	panic(err)
}
```
[Go Playground](https://go.dev/play/p/fVTZsYa3c_v)

I think it can be further minimized to unmarshaling only the string itself:

```go
var a ma.Multiaddr
b := []byte(`"/ip4/64.227.126.216/tcp/4001"`)
if err := json.Unmarshal(b, &a); err != nil {
	panic(err)
}
```

Here I'm getting `json: cannot unmarshal string into Go value of type multiaddr.Multiaddr`.

I see implementations of json marshaling in `ma.Multiaddr`, so I wonder if I'm doing something wrong?

**Comment by mg98** [comment]
Hmm I see already, it must be because `ma.Multiaddr` is an interface and the exact type is not known.

**Comment by mg98** [comment]
Would like to reopen this... I highly advocate getting rid of the interface here and just sticking with a struct!
Also found in relation to this issue: https://github.com/multiformats/go-multiaddr/issues/100

**Comment by marten-seemann** [comment]
👋 libp2p maintainer here.

I suggest closing this issue, since this seems to be exactly what #100 is about.

The core team won't have any capacity to resolve this issue any time soon, but we're happy to review a proposal and a PR. @mg98, would you mind commenting on #100 how exactly you'd like to solve this, so we can get the discussion going?
